version: "3.8"
services:
  next-app:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - image_server

  image_server:
    build:
      context: ./images
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    volumes:
      - booking_images2:/app/images/uploads

  mongodb:
    image: mongo
    container_name: booking2_mongodb
    ports:
      - "27017:27017"
    volumes:
      - booking5_mongodb_data:/data/db

volumes:
  booking5_mongodb_data:
  booking_images2:
